# Generated by Django 5.0.7 on 2024-08-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
